const gameGenres = {
    "subway.html": ["arcade", "action"],
    "basket.html": ["sports", "arcade", "multiplayer"],
    "retrobowl.html": ["sports", "simulation", "arcade"],
    "slope.html": ["arcade", "action"],
    "stacktris.html": ["puzzle", "arcade"],
    "run3.html": ["arcade", "platformer"],
    "brubber.html": ["racing", "action"],
    "finalearth2.html": ["strategy", "simulation"],
    "minecraft.html": ["simulation", "sandbox"],
    "eaglercraft.html": ["simulation", "sandbox"],
    "fishing.html": ["idle", "simulation"],
    "burgeria.html": ["simulation", "strategy"],
    "freezeria.html": ["simulation", "strategy"],
    "pizzeria.html": ["simulation", "strategy"],
    "hotdoggeria.html": ["simulation", "strategy"],
    "sushiria.html": ["simulation", "strategy"],
    "drivemad.html": ["racing", "puzzle"],
    "hoverracer.html": ["racing", "arcade"],
    "stickman.html": ["arcade", "action"],
    "dice.html": ["idle", "puzzle"],
    "gladihoppers.html": ["action", "arcade"],
    "flappybasketball.html": ["arcade", "sports"],
    "tunnel.html": ["arcade", "action"],
    "getaway.html": ["action", "shooter"],
    "gobdun.html": ["rpg", "action"],
    "minimetro.html": ["puzzle", "strategy"],
    "btd4.html": ["strategy", "action"],
    "btd5.html": ["strategy", "action"],
    "pokemonfr.html": ["rpg", "strategy"],
    "pokemonem.html": ["rpg", "strategy"],
    "pokemonplat.html": ["rpg", "strategy"],
    "pokemonsoulsilver.html": ["rpg", "strategy"],
    "pokemonblk.html": ["rpg", "strategy"],
    "mariokartds.html": ["racing", "arcade"],
    "gtachina.html": ["action", "shooter"],
    "fred.html": ["arcade", "action"],
    "crazycattle.html": ["arcade", "action"],
    "blumgiball.html": ["sports", "arcade"],
    "jacksmith.html": ["strategy", "simulation"],
    "gswitch.html": ["arcade", "platformer", "multiplayer"],
    "pvz.html": ["strategy", "action"],
    "basketstars.html": ["sports", "arcade"],
    "totm.html": ["arcade", "action"],
    "breakout.html": ["idle", "arcade"],
    "crossyroads.html": ["arcade", "action"],
    "la2.html": ["puzzle", "simulation"],
    "sideeffects.html": ["horror", "arcade"],
    "tag.html": ["action", "arcade", "multiplayer"],
    "shogunshowdown.html": ["strategy", "rpg"],
    "operius.html": ["arcade", "shooter"],
    "https://harshulsilverspoon.github.io/cookieclickeriframe.html/": ["idle", "simulation"],
    "motox3m.html": ["racing", "arcade"],
    "portal.html": ["puzzle", "platformer"],
    "vampire.html": ["action", "rpg"],
    "leveldevil.html": ["puzzle", "platformer"],
    "fnaf1.html": ["horror", "action"],
    "fnaf2.html": ["horror", "action"],
    "fnaf3.html": ["horror", "action"],
    "fnaf4.html": ["horror", "action"],
    "fnafps.html": ["horror", "simulation"],
    "fnafucn.html": ["horror", "action"],
    "https://harshulsilverspoon.github.io/codzombies": ["shooter", "horror", "action"],
    "badguards.html": ["action", "shooter"],
    "dire.html": ["strategy", "rpg"],
    "bloxorz.html": ["puzzle"],
    "suika.html": ["puzzle", "arcade"],
    "frontwars.html": ["strategy"],
    "antimatter.html": ["idle", "simulation"],
    "snowrider.html": ["racing", "arcade"],
    "gunmayhem.html": ["shooter", "action", "multiplayer"],
    "gunmayhem2.html": ["shooter", "action", "multiplayer"],
    "polytrack.html": ["racing", "arcade"],
    "bitlife.html": ["simulation"],
    "ageofwar.html": ["strategy", "action"],
    "ultrakillweb.html": ["shooter", "action"],
    "learntofly1.html": ["strategy", "arcade"],
    "learntofly2.html": ["strategy", "arcade"],
    "learntofly.html": ["strategy", "arcade"],
    "learntoflyidle.html": ["idle", "arcade"],
    "fireboy.html": ["puzzle", "platformer", "multiplayer"],
    "fireboy2.html": ["puzzle", "platformer", "multiplayer"],
    "fireboy3.html": ["puzzle", "platformer", "multiplayer"],
    "happywheels.html": ["action", "arcade"],
    "hollowknight.html": ["platformer", "action", "rpg"],
    "silksong.html": ["platformer", "action", "rpg"],
    "doom.html": ["shooter", "action"],
    "cluster.html": ["arcade", "action"],
    "fnae.html": ["horror", "action"],
    "worldbox.html": ["simulation", "strategy"],
    "burritobison.html": ["arcade", "action"],
    "badtime.html": ["action", "arcade"],
    "deltarune.html": ["rpg"],
    "earntodie.html": ["racing", "action"],
    "rocketleague.html": ["sports", "racing"],
    "bankrobbery2.html": ["action", "shooter"],
    "spacewaves.html": ["arcade", "music"],
    "soccerrandom.html": ["sports", "arcade", "multiplayer"],
    "volleyrandom.html": ["sports", "arcade", "multiplayer"],
    "boxingrandom.html": ["sports", "arcade", "multiplayer"],
    "fnf.html": ["music", "arcade"],
    "classof09.html": ["simulation", "rpg"],
    "nubbysnumberfactory.html": ["roguelike", "arcade"],
    "isaac.html": ["action", "rpg", "horror", "roguelike"],
    "supersmashflash2.html": ["action", "arcade"],
    "papersplease.html": ["puzzle", "simulation"],
    "diceamillion.html": ["roguelike"],
    "pizzatower.html": ["platformer", "action"],
    "cloverpit.html": ["strategy", "roguelike"],
    "celeste.html": ["platformer", "action"],
    "balatro.html": ["strategy", "roguelike"],
    "dungeonsgambler.html": ["strategy", "roguelike"],
    "5b.html": ["platformer", "puzzle"],
    "osu.html": ["music", "arcade"],
    "halflife.html": ["shooter", "action"],
    "shapez.html": ["puzzle", "simulation"],
    "feedthevoid.html": ["strategy"],
    "peopleplayground.html": ["simulation", "sandbox"],
    "repo.html": ["horror", "action", "roguelike"],
    "geometrydash.html": ["arcade", "music", "platformer"],
    "statetris-europe.html": ["puzzle", "arcade"],
    "fearandhunger.html": ["rpg", "horror"],
    "yomihustle": ["action", "strategy"],
    "ducklife1.html": ["simulation", "sports"],
    "ducklife2.html": ["simulation", "sports"],
    "ducklife3.html": ["simulation", "sports"],
    "ducklife4.html": ["simulation", "sports"],
    "sonicexe.html": ["horror", "platformer"],
    "ultrapool.html": ["sports", "arcade"]
    "baseballbros.html": ["sports"]
};
