const gameNames = {
    "subway.html": "subway surfers",
    "basket.html": "basket random basketball",
    "retrobowl.html": "retro bowl football",
    "slope.html": "slope",
    "stacktris.html": "stacktris tetris",
    "run3.html": "run 3",
    "brubber.html": "burning rubber",
    "finalearth2.html": "final earth 2",
    "minecraft.html": "minecraft",
    "eaglercraft.html": "eaglercraft minecraft",
    "fishing.html": "tiny fishing",
    "burgeria.html": "papas burgeria papa's",
    "freezeria.html": "papas freezeria papa's",
    "pizzeria.html": "papas pizzeria papa's",
    "hotdoggeria.html": "papas hot doggeria papa's",
    "sushiria.html": "papas sushiria papa's",
    "drivemad.html": "drive mad",
    "hoverracer.html": "hover racer drive",
    "stickman.html": "stickman hook",
    "dice.html": "idle dice",
    "gladihoppers.html": "gladihoppers",
    "flappybasketball.html": "flappy basketball",
    "tunnel.html": "tunnel rush",
    "getaway.html": "getaway shootout",
    "gobdun.html": "gobdun",
    "minimetro.html": "mini metro",
    "btd4.html": "bloons tower defense 4 btd4",
    "btd5.html": "bloons tower defense 5 btd5",
    "pokemonfr.html": "pokemon fire red",
    "pokemonem.html": "pokemon emerald",
    "pokemonplat.html": "pokemon platinum",
    "pokemonsoulsilver.html": "pokemon soulsilver soul silver",
    "pokemonblk.html": "pokemon black",
    "mariokartds.html": "mario kart ds",
    "gtachina.html": "gta chinatown wars grand theft auto",
    "fred.html": "skiing fred",
    "crazycattle.html": "crazy cattle 3d",
    "blumgiball.html": "blumgi ball",
    "jacksmith.html": "jacksmith",
    "gswitch.html": "g switch 3",
    "pvz.html": "plants vs zombies pvz",
    "basketstars.html": "basketball stars",
    "totm.html": "tomb of the mask",
    "breakout.html": "idle breakout",
    "crossyroads.html": "crossy road",
    "la2.html": "little alchemy 2",
    "sideeffects.html": "side effects",
    "tag.html": "tag",
    "shogunshowdown.html": "shogun showdown",
    "operius.html": "operius",
    "https://harshulsilverspoon.github.io/cookieclickeriframe.html/": "cookie clicker",
    "motox3m.html": "moto x3m",
    "portal.html": "portal",
    "vampire.html": "vampire survivors",
    "leveldevil.html": "level devil",
    "fnaf1.html": "five nights at freddys 1 fnaf",
    "fnaf2.html": "five nights at freddys 2 fnaf",
    "fnaf3.html": "five nights at freddys 3 fnaf",
    "fnaf4.html": "five nights at freddys 4 fnaf",
    "fnafucn.html": "five nights at freddys fnaf ucn ultimate custom night",
    "fnafps.html": "five nights at freddys pizza simulator fnaf",
    "https://harshulsilverspoon.github.io/codzombies": "call of duty zombies cod nacht",
    "badguards.html": "bad guards",
    "dire.html": "dire decks",
    "bloxorz.html": "bloxorz",
    "suika.html": "suika watermelon game",
    "frontwars.html": "front wars",
    "antimatter.html": "antimatter dimensions",
    "snowrider.html": "snow rider 3d",
    "gunmayhem.html": "gun mayhem",
    "gunmayhem2.html": "gun mayhem 2",
    "polytrack.html": "polytrack racing",
    "bitlife.html": "bitlife life simulator",
    "ageofwar.html": "age of war",
    "ultrakillweb.html": "ultrakill",
    "learntofly1.html": "learn to fly 1",
    "learntofly2.html": "learn to fly 2",
    "learntofly.html": "learn to fly 3",
    "learntoflyidle.html": "learn to fly idle",
    "fireboy.html": "fireboy and watergirl 1",
    "fireboy2.html": "fireboy and watergirl 2",
    "fireboy3.html": "fireboy and watergirl 3",
    "happywheels.html": "happy wheels",
    "hollowknight.html": "hollow knight",
    "silksong.html": "hollow knight silksong",
    "doom.html": "doom",
    "cluster.html": "cluster rush",
    "fnae.html": "five nights at epsteins epstein's fnae",
    "worldbox.html": "worldbox god simulator",
    "burritobison.html": "burrito bison",
    "badtime.html": "bad time simulator sans undertale",
    "deltarune.html": "deltarune undertale",
    "earntodie.html": "earn to die",
    "rocketleague.html": "rocket league",
    "bankrobbery2.html": "bank robbery 2",
    "spacewaves.html": "space waves geometry dash",
    "soccerrandom.html": "soccer random",
    "volleyrandom.html": "volley random volleyball",
    "boxingrandom.html": "boxing random",
    "fnf.html": "friday night funkin fnf",
    "classof09.html": "class of 09 '09",
    "nubbysnumberfactory.html": "nubbys number factory nubby's",
    "isaac.html": "the binding of isaac wrath of the lamb",
    "supersmashflash2.html": "super smash flash 2 super smash bros ssf2",
    "papersplease.html": "papers please",
    "diceamillion.html": "dice a million",
    "pizzatower.html": "pizza tower",
    "cloverpit.html": "cloverpit clover pit",
    "celeste.html": "celeste",
    "balatro.html": "balatro",
    "dungeonsgambler.html": "dungeons and degenerate gamblers",
    "5b.html": "battle for dream island again 5b bfdia 5b",
    "osu.html": "osu!",
    "halflife.html": "half life halflife",
    "shapez.html": "shapez.io",
    "feedthevoid.html": "feed the void",
    "peopleplayground.html": "people playground",
    "geometrydash.html": "geometry dash",
    "repo.html": "repo r.e.p.o",
    "statetris-europe.html": "statetris europe tetris",
    "fearandhunger.html": "fear and hunger",
    "yomihustle": "your only move is hustle yomi hustle",
    "ducklife1.html": "ducklife 1 duck life",
    "ducklife2.html": "ducklife 2 duck life",
    "ducklife3.html": "ducklife 3 duck life",
    "ducklife4.html": "ducklife 4 duck life",
    "sonicexe.html": "sonic exe sonic.exe",
    "ultrapool.html": "ultrapool ultra pool"
};
